### ISSUE TITLE
Cpu usage increase over time

### ISSUE THREAD

**Issue by LorenzoRogai** [KenT2/tboplayer#4] opened 2014-05-12 08:23 UTC
Hi i noticed while playing videos the tboplayer.py process starts taking more and more cpu over time
If i stop the video it returns to 0-1%
![tboplayer1](https://cloud.githubusercontent.com/assets/1665768/2942022/9e54c0fc-d9ae-11e3-8c29-b9d5e24a635d.PNG)

After 20 minutes

![tboplayer2](https://cloud.githubusercontent.com/assets/1665768/2942023/9e591120-d9ae-11e3-8bcf-0fd4fafa80b4.PNG)

Any solution?

**Comment by heniotierra** [comment] 2015-09-16 19:33
Just a guess, I think this might be caused by infinitely looping threads?
Specifically the thread for the ```_get_position``` functions, which is responsible for updating playing time. If that's the case, then I probably fixed it some days ago, making that function's loop to stop once omxplayer process closes.
Could you please verify this, @LorenzoRogai ?

**Comment by LorenzoRogai** [comment] 2015-09-16 19:50
@heniotierra Sorry but at the moment i'm using the raspberry as a server without the gui

**Comment by heniotierra** [comment] 2015-09-16 20:13
That's fine. Well, I guess I'll just close this issue as solved then, since CPU usage keeps low all the time for me and I fixed that endless loop. Thank you.

**Closed by heniotierra** 2015-09-16 20:13 UTC
