### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Botspot** [KenT2/tboplayer#185] opened 2020-09-21 22:08 UTC
I am developing a RPi app store and I plan to include this software.
When users click "install", the app store will then clone your repository and run your recommended install commands.

One problem though: it needs a unique icon. Does tboplayer have an icon? If not then I'll have to leave it blank.

**Comment by heniotierra** [comment] 2020-09-22 01:09
That's nice! I suggest you add the python 2 version, since it's much more stable.
Well, I'm not a good designer, but I can make a simple icon for the program, sure!

**Comment by Botspot** [comment] 2020-09-22 01:24
Thank you! I myself have designed several good-looking logos, and if you'd like I can give feedback & offer suggestions.

Speaking of stability, a while back I had an issue searching youtube with tboplayer where the search results would never show up. Are you aware of that bug? If not, never mind and don't worry about it.

**Comment by heniotierra** [comment] 2020-09-22 01:29
Sure, I appreciate the help on the icon!

I am aware of this bug. The cause is that Youtube changed its search results page, so the script that was made to crawl it does not work anymore. I opened an issue reporting this problem today. This also happens in the python 2 version.

**Comment by Botspot** [comment] 2020-09-22 01:31
Great! You know what, I could design the whole icon for you if you want. Just give me a rough idea of what it should look like,

**Comment by heniotierra** [comment] 2020-09-22 01:39
That would be great! I thought of something really simple, maybe with a light blue font and transparent background, like this.

![image](https://user-images.githubusercontent.com/4629295/93837036-1bfcd780-fc5b-11ea-8d72-ee370832b496.png)

**Comment by Botspot** [comment] 2020-09-22 02:12
What does TBO stand for?

**Comment by heniotierra** [comment] 2020-09-22 02:46
Good question. Maybe @KenT2 can answer that. hehe

**Comment by KenT2** [comment] 2020-09-22 06:19
Thompson Baiter Omxplayer

**Comment by Botspot** [comment] 2020-09-22 13:21
I'm afraid your logo won't be suitable as an icon. It's a good start, but we have to remember it must be recognizable at small sizes.
This square below is the size of an icon.
![24x24](https://user-images.githubusercontent.com/54716352/93887328-2eebc800-fcac-11ea-8b2d-82163dffeb00.png)
And scaling yours down would make it hard to read:
![24x24](https://user-images.githubusercontent.com/54716352/93887673-9d308a80-fcac-11ea-9da5-f8ee8e33f0b5.png)

**Comment by Botspot** [comment] 2020-09-22 15:18
OK, let me know what you think of these:
![tbo1](https://user-images.githubusercontent.com/54716352/93902129-d7a22380-fcbc-11ea-9bfd-b31cf6c33c8f.png)
![tbo2](https://user-images.githubusercontent.com/54716352/93902132-d83aba00-fcbc-11ea-9ac9-f8b161047d78.png)

**Comment by Botspot** [comment] 2020-09-22 15:44
![2020-09-22-104157_1280x1024_scrot](https://user-images.githubusercontent.com/54716352/93905389-8b58e280-fcc0-11ea-997c-a69dbb621c59.png)

**Comment by heniotierra** [comment] 2020-09-22 16:11
Ooh, nice! I like the middle one better. 
![image](https://user-images.githubusercontent.com/4629295/93908135-a6355200-fcd4-11ea-91f0-c1e3b3d4622e.png)

BTW, you read my mind! I was thinking of something along these lines! :D

But I'd use the color scheme in here 

![image](https://user-images.githubusercontent.com/4629295/93908258-ccf38880-fcd4-11ea-846a-7ab447078ee5.png)

because using the inside of the circle in red seems like a reference to Youtube.

**Comment by Botspot** [comment] 2020-09-22 16:25
Well, it **is** a reference to YouTube. :) Because TBOplayer can play youtube.
I prefer the outer circle being black, as it comes across more as an O than otherwise.

If you don't like the reference to YouTube, we could change the color:
![2020-09-22-112350_1280x1024_scrot](https://user-images.githubusercontent.com/54716352/93910079-34eea280-fcc6-11ea-8367-61c3f6e87fb3.png)

**Comment by heniotierra** [comment] 2020-09-22 17:08
Well, yes, it can play Youtube, but it can also play all of the most popular streaming services (last time I checked), that's why I thought of not making this reference. But I loved the icon! And I guess the reference doesn't hurt.

I like these two:
![image](https://user-images.githubusercontent.com/4629295/93913481-881f2000-fcdb-11ea-9b62-fb484d0e26c3.png)

![image](https://user-images.githubusercontent.com/4629295/93913592-adac2980-fcdb-11ea-85a2-04b97611a45f.png)

Ok, vote for the red one because it draws more attention. :)

Hey @KenT2 , would you have an opinion?

**Comment by heniotierra** [comment] 2020-09-22 17:15
> Well, yes, it can play Youtube, but it can also play all of the most popular streaming services (last time I checked), that's why I thought of not making this reference. But I loved the icon! And I guess the reference doesn't hurt.
> 
> I like these two:
> ![image](https://user-images.githubusercontent.com/4629295/93913481-881f2000-fcdb-11ea-9b62-fb484d0e26c3.png)
> 
> ![image](https://user-images.githubusercontent.com/4629295/93913592-adac2980-fcdb-11ea-85a2-04b97611a45f.png)
> 
> Ok, vote for the red one because it draws more attention. :)
> 
> Hey @KenT2 , would you have an opinion?

**Comment by Botspot** [comment] 2020-09-23 20:58
@KenT2 @heniotierra Have we made a decision yet?

**Comment by heniotierra** [comment] 2020-09-23 22:29
I guess we can go with the red one. :)

**Comment by Botspot** [comment] 2020-09-23 22:44
OK. Attached is a zip file containing a bunch of sizes of your new icon.
Thank you.
[tbo.zip](https://github.com/KenT2/tboplayer/files/5272362/tbo.zip)

**Comment by heniotierra** [comment] 2020-09-23 22:52
Thank YOU for your work!

**Comment by heniotierra** [comment] 2020-09-23 22:54
@Botspot please, send an email if you need anyhting specific from me to make TBOPlayer installer work on the store you're building. It's heniotster at gmail dot com.

**Comment by Botspot** [comment] 2020-10-03 17:34
I sent you an email over a week ago. Have you seen it?
Basically, I'd like to see TBOPlayer ship with the new icon. (it would look a lot prettier than the python logo it has now)
And I also noticed that after installation, a mystery menu button appeared: Pure Data. What is it, and can `puredata` be uninstalled safely?

**Comment by heniotierra** [comment] 2020-10-03 17:48
Hi @Botspot ! Your email never arrived. 
Puredata? I don't see how that could be related to TBOPlayer. Try to open the shortcut with the text editor to see its contents. You can find such files under path `/usr/share/applications`.
About the icon, I should do that this weekend. I just haven't been having much free time as of late.

**Comment by heniotierra** [comment] 2020-10-03 17:54
Also, for transparency sake, I must say I'll dump the Python 3 version in favor of the python 2 one. The reason for that being that  OMXPlayer will be discontinued as can be seen in its github page, thus I don't think it's worth investing much in a Python 3 version. However, I should still fix and maintain the Python 2 version as long as OMXPlayer still works and has users. The efforts put into OMXPlayer will be put on developing VLC.

**Comment by Botspot** [comment] 2020-10-03 18:41
The Pure Data thing appeared in the menu at the same time I installed TBOPlayer. I would assume one of your APT dependencies managed to install it.

Looking forward to the icon change. :)

OK. Well I've already taken your suggestion and am using the Py2 version.

**Comment by heniotierra** [comment] 2020-10-03 20:43
Maybe it's some dependency doing that, yeah. Can you try to investigate that button? If it's showing in the menu, it's most probably present in the path I mentioned. By looking as its code through the text editor you should be able to know its source. You can paste the content here too, so I can take a look.

**Comment by Botspot** [comment] 2020-10-03 21:12
I can check it later, but it did go away after I ran:

    sudo apt purge puredata

**Comment by Botspot** [comment] 2020-10-03 21:31
Okay, I found it.
The rogue menu button is created at `/usr/share/applications/puredata.desktop`.
I uninstalled the `puredata` package, then ran the tboplayer install script. Sure enough, puredata was there again.

**Comment by Botspot** [comment] 2020-10-03 21:32
And this is the contents of `/usr/share/applications/puredata.desktop`: 
```
[Desktop Entry]
Type=Application
Name=Pure Data
GenericName=Pd
Comment=Visual dataflow programming platform for multimedia
Comment[ca]=Plataforma de programació visual per aplicacions multimèdia
Comment[de]=Grafische Datenflussprogrammierung für Multimedia
Comment[es]=Plataforma de programación visual para aplicaciones multimedia
Comment[fr]=Plateforme de programmation visuelle pour applications multimédia
Comment[it]=Piattaforma di programmazione visuale per applicazioni multimedia
Comment[pt]=Plataforma de programação visuais para multimedia
Icon=puredata.xpm
Exec=/usr/lib/puredata/tcl/pd-gui.tcl %F
Terminal=false
Categories=AudioVideo;Audio;
MimeType=text/x-puredata;text/x-maxmsp;
Keywords=Audio;Video;Programming;Synthesis;Analysis
```

**Comment by heniotierra** [comment] 2020-10-03 21:36
Ok, thanks. I'll look into that.

**Comment by Botspot** [comment] 2020-10-03 23:03
Yep - looks to be a dependency problem.
When I install TBO's dependencies manually beforehand, I get:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gem gem-doc gem-extra gem-plugin-assimp gem-plugin-gmerlin gem-plugin-lqt
  gem-plugin-magick gem-plugin-v4l2 libassimp4 libftgl2 libgavl1 libglewmx1.13
  libgmerlin-avdec1 libmagick++-6.q16-8 libquicktime2 pd-libdir puredata
  puredata-core puredata-dev puredata-doc puredata-extra puredata-gui
  puredata-gui-l10n puredata-import puredata-utils
Suggested packages:
  pd-zexy v4l2loopback-dkms | v4l2loopback-modules pd-aubio pd-csound pd-pdp
  multimedia-puredata python-gobject-2-dbg python-gtk2-doc python-socks tix
  python-tk-dbg
The following NEW packages will be installed:
  gem gem-doc gem-extra gem-plugin-assimp gem-plugin-gmerlin gem-plugin-lqt
  gem-plugin-magick gem-plugin-v4l2 libassimp4 libftgl2 libgavl1 libglewmx1.13
  libgmerlin-avdec1 libmagick++-6.q16-8 libquicktime2 pd-libdir puredata
  puredata-core puredata-dev puredata-doc puredata-extra puredata-gui
  puredata-gui-l10n puredata-import puredata-utils python-gobject-2
  python-gtk2 python-requests python-tk tkdnd
```

**Comment by Botspot** [comment] 2020-10-03 23:41
BINGO! I'll let the apt output speak for itself:
```
pi@raspberrypi:~ $ sudo apt-get install tkdnd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  gem gem-doc gem-extra gem-plugin-assimp gem-plugin-gmerlin gem-plugin-lqt
  gem-plugin-magick gem-plugin-v4l2 libassimp4 libftgl2 libgavl1 libglewmx1.13
  libgmerlin-avdec1 libmagick++-6.q16-8 libquicktime2 pd-libdir puredata
  puredata-core puredata-dev puredata-doc puredata-extra puredata-gui
  puredata-gui-l10n puredata-import puredata-utils
Suggested packages:
  pd-zexy v4l2loopback-dkms | v4l2loopback-modules pd-aubio pd-csound pd-pdp
  multimedia-puredata
The following NEW packages will be installed:
  gem gem-doc gem-extra gem-plugin-assimp gem-plugin-gmerlin gem-plugin-lqt
  gem-plugin-magick gem-plugin-v4l2 libassimp4 libftgl2 libgavl1 libglewmx1.13
  libgmerlin-avdec1 libmagick++-6.q16-8 libquicktime2 pd-libdir puredata
  puredata-core puredata-dev puredata-doc puredata-extra puredata-gui
  puredata-gui-l10n puredata-import puredata-utils tkdnd
0 upgraded, 26 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.4 MB of archives.
After this operation, 32.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
(I found that the package `tkdnd` is to blame, as it's the one that installs `puredata`)

**Comment by Botspot** [comment] 2020-10-03 23:48
An update: using `apt` with `--no-install-recommends` for `tkdnd` appears to work OK for TBOPlayer.

**Comment by heniotierra** [comment] 2020-10-04 00:29
That's nice @Botspot ! Thank you again for your help! :)

**Comment by heniotierra** [comment] 2020-10-04 22:33
@Botspot , will you need any icon size different 24x24? If not, I'll leave only the images with this size and another one for the readme.

**Comment by heniotierra** [comment] 2020-10-04 23:32
@Botspot The changes were merged. Next I'll fix the Youtube search and move the py2_version branch to master.

**Closed by heniotierra** 2020-10-04 23:32 UTC

**Comment by Botspot** [comment] 2020-10-04 23:56
> @Botspot , will you need any icon size different 24x24?
Not sure what you mean

**Comment by heniotierra** [comment] 2020-10-04 23:58
I meant for the app store. I left three icon sizes there: 24x24, 48x48, 128x128.

**Comment by Botspot** [comment] 2020-10-05 00:05
Oh don't worry. I have all the icon sizes I need.

**Comment by Botspot** [comment] 2020-10-05 02:44
BTW, here's my app store: https://github.com/Botspot/pi-apps

**Comment by Botspot** [comment] 2020-10-05 03:05
Hey, could you also add the icon to the running program's icon? (the icon that's displayed in the panel while TBOplayer is running)
Screenshot below:
![2020-10-04-220007_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/95036477-b1ea2680-068d-11eb-8574-fc73b7089452.png)

**Comment by heniotierra** [comment] 2020-10-05 03:06
> BTW, here's my app store: https://github.com/Botspot/pi-apps
Cool, will have a look. Thank you for the link! :) 
> Hey, could you also add the icon to the running program's icon? (the icon that's displayed in the panel while TBOplayer is running)
Screenshot below:
Yep, it's in my to-do list.

**Comment by heniotierra** [comment] 2020-10-05 03:25
@Botspot There it is: Fixed the youtube search feature, and added the icon to the window. Tomorrow I should replace the master branch.

**Comment by heniotierra** [comment] 2020-10-05 03:31
Oh, and it's such a great idea that app of yours!

**Comment by heniotierra** [comment] 2020-10-05 03:34
I'll update this thread when I replace the master branch code.

**Comment by Botspot** [comment] 2020-10-05 13:47
It's not working for me.
```
pi@raspberrypi:~ $ python /opt/tboplayer/tboplayer.py
Traceback (most recent call last):
  File "/opt/tboplayer/tboplayer.py", line 75, in <module>
    from youtubesearchpython import SearchVideos
ImportError: No module named youtubesearchpython
```

**Comment by heniotierra** [comment] 2020-10-05 13:55
@Botspot DId you run the setup again? The new required lib can be installed with:

    pip install --user youtube-search-python

**Comment by heniotierra** [comment] 2020-10-05 17:22
@Botspot  there was a problem with this package installation in the setup script. That should be fixed now.0

**Comment by Botspot** [comment] 2020-10-12 17:13
Thank you one more time for all your help.
For future reference, I'm uploading the original vector TBOPlayer icon. It's in SVG format so you could turn it into any size icon you could ever want. (or change the colors if you had a SVG editor)
[tbo.svg.zip](https://github.com/KenT2/tboplayer/files/5366484/tbo.svg.zip)

**Comment by heniotierra** [comment] 2020-10-25 23:27
Hey @Botspot , I think tkinter does not allow SVG for window icons, at least the python2 tkinter.

**Comment by Botspot** [comment] 2020-10-25 23:47
> Hey @Botspot , I think tkinter does not allow SVG for window icons, at least the python2 tkinter. But thank you, that may come in handy in the future.

I understand that. But, a SVG comes in useful because SVGs aren't made up of pixels: instead they are vectors. So with a SVG image, you can *export* it to any size PNG you want, and the edges of the shapes will always stay clear.

Let's say 5 years down the road: you may want a 1024x1024 icon, but I am long gone. With a SVG, it's really easy: just opent he SVG in Inkscape or an equivalent, and you have your 1024x1024 png image.  
But if I never gave you that SVG, you would simply not be able to get a 1024x1024 image - or if you were, it would be badly pixelated.

Sending you the SVG ensures you can generate any icon size you want, without relying on me. Make sense?

**Comment by heniotierra** [comment] 2020-10-26 00:06
@Botspot  OFC, that's why I said it might come in handy in the future.
BTW, just to let you know, I replaced the master branch with the python 2 version as I said I would.
